#!/usr/bin/env bash

# Install nginx on the server
apt-get -y update
apt-get -y install nginx

# Get the hostname of the server
HOST_NAME=$(hostname)

# Configure Nginx to add custom response header
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Add custom response header
    add_header X-Served-By $HOST_NAME;
}
" > /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart

