#!/usr/bin/env bash

# Install HAProxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
cat << EOF > /etc/haproxy/haproxy.cfg
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server STUDENT_ID-web-01 [web-01-IP]:80 check
        server STUDENT_ID-web-02 [web-02-IP]:80 check
EOF

# Restart HAproxy service
systemctl restart haproxy

